apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bbox-root
  name: bbox-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbox-root
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bbox-root
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
        - /bin/sh
        - -c
        - sleep 1000
        resources: {}
status: {}
