apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bbox-noroot
  name: bbox-noroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbox-noroot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bbox-noroot
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: busybox
        name: busybox
        command:
        - /bin/sh
        - -c
        - sleep 1000
        resources: {}
status: {}
