apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
spec:
  nodeName: worker1
  containers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      while true; do
        echo "This is sa-pod at $(date)"
        sleep 30
      done


