apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to GREEN.COM</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body style="background-color:MediumSeaGreen;">
    <h1>Welcome to GREEN.COM</h1>
    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: greenindex
---
apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to RED.COM</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body style="background-color:Tomato;">
    <h1>Welcome to RED.COM</h1>
    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: redindex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: green
  name: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green
  strategy:
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: green
    spec:
      volumes:
      - configMap:
          name: greenindex
        name: green-index
      imagePullSecrets:
      - name: regcred
      containers:
      - image: docker.io/kwaberski/test:3.0
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: green-index
          mountPath: /usr/share/nginx/html
          readOnly: true
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: red
  name: red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: red
  strategy:
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: red
    spec:
      volumes:
      - configMap:
          name: redindex
        name: red-index
      initContainers:
      - name: init-1
        image: busybox
        command: ['sh', '-c', "until nslookup red.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: red-index
          mountPath: /usr/share/nginx/html
          readOnly: true
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: green
  name: green
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: green
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: red
  name: red
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: red
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vhost
spec:
  rules:
  - host: green.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: green
            port:
              number: 80
  - host: red.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: red
            port:
              number: 80
