apiVersion: v1
kind: Pod
metadata:
  name: bbox-sec
spec:
  serviceAccount: sa1
  volumes:
  - name: secret
    secret:
      secretName: secret1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - image: busybox
    name: busybox
    command:
    - /bin/sh
    - -c
    - sleep 1000
    volumeMounts:
    - name: secret
      mountPath: /etc/secret
      readOnly: true
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: secret2
          key: user 
