network:
  renderer: networkd
  version: 2
  ethernets:
    ens160:
      addresses: [${h_ip}/${h_mask}]
      gateway4: ${h_gw}
      nameservers:
        search: [corp.guardanet.net]
        addresses:
          - ${h_gw}
          - 8.8.8.8
          - 8.8.4.4
