apiVersion: v1
data:
  index.html: |

    <!DOCTYPE html>
    <html>
    <body style="background-color:powderblue;">

    <h1>This is a heading</h1>
    <p>This is a paragraph.</p>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: mainpage
