---
apiVersion: v1
data:
  index.html: |

    <!DOCTYPE html>
    <html>
    <body style="background-color:powderblue;">

    <h1>Welcome to NGINX WebServer</h1>
    <p>Version: 1.0</p>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: mainpage
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: 1.19.2
spec:
  volumes:
    - name: mainpage
      configMap:
        name: mainpage
  containers:
    - name: my-nginx
      image: nginx:1.19.2
      volumeMounts:
        - name: mainpage
          mountPath: /usr/share/nginx/html
      ports:
      - containerPort: 80
      resources:
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
