apiVersion: v1
kind: Pod
metadata:
  name: mitm
  labels:
    app: mitm
spec:
  containers:
  - name: mitm
    image: docker.io/mitmproxy/mitmproxy
    command: ["mitmdump","--mode reverse:http://10.96.118.90 --flow-detail 3"]
#    command: ["mitmdump","--mode socks5 --showhost --flow-detail 3 --set block_global=false"]
    ports:
    - name: http
      containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mitm
spec:
  selector:
    app: mitm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: proxy
  type: ClusterIP
  externalIPs:
    - 172.16.106.24
    - 172.16.54.188