apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ephemeral-demo
  name: ephemeral-demo
spec:
  nodeName: c1w1
  containers:
  - image: k8s.gcr.io/pause:3.1
    name: ephemeral-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
