apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /nfs_share
    server: 10.0.0.5
  mountOptions:
  - hard
  - nfsvers=4.1
