apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-env
  name: test-env
spec:
  containers:
  - image: busybox
    name: test
    command:
    - sh
    - -c 
    - |
      printf $URL1
      printf $URL2
      printf $URL3
    env:
    - name: PROTO
      value: "https"
    - name: DEST
      value: "kubernetes"
    - name: PORT
      value: "443"
    - name: URL1
      value: "$(PROTO)://$(DEST):$(PORT)"
    - name: URL2
      value: "$(PROTO)://$(DEST):$(SERV_PORT)"
    - name: URL3
      value: "$$(PROTO)://$(DEST):$(PORT)"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
