apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dns-pod
  name: dns-pod
spec:
  hostAliases:
  - ip: "192.168.2.1"
    hostnames: ["vmh"]
  containers:
  - image: busybox
    name: dns-pod
    command:
    - /bin/sh
    - -c
    - |
      echo "Here is my hosts file"
      cat /etc/hosts
      sleep 300
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
