apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: attack-pod
  name: attack-pod
spec:
  containers:
  - image: raesene/alpine-nettools
    name: attack-pod
    securityContext:
      privileged: true
    ports:
    - name: ssh
      containerPort: 22 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
