apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-pod
  name: my-pod
spec:
  containers:
  - image: ubuntu
    name: my-pod
    command: ["/bin/sh","-c","sleep 1d"]
    ports:
    - name: ssh
      containerPort: 22 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
