apiVersion: v1
kind: Pod
metadata:
  name: bbox-cmd
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - image: busybox
    name: busybox
    command:
    - /bin/sh
    - -c
    - |
      /bin/sh <<EOF
      echo Hi from my script
      hostname
      env
      sleep 60
      EOF
