apiVersion: v1
kind: Pod
metadata:
  name: bbox-info
spec:
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - image: busybox
    name: busybox
    command:
    - /bin/sh
    - -c
    - |
      while true; 
      do
        echo "Mem: $MEM";
        echo "Cpu: $CPU";
        echo "IP: $IP";
        echo "POD: $POD";
        echo "NODE: $NODE";
        echo "LABELS:"; cat /etc/podinfo/labels;
        echo "ANNOTATIONS:"; cat /etc/podinfo/annotations;
        sleep 60;
      done;
    resources:
      requests:
        memory: "32Mi"
        cpu: "125m"
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
    env:
    - name: MEM
      valueFrom:
        resourceFieldRef: 
          containerName: busybox
          resource: requests.memory
    - name: CPU
      valueFrom:
        resourceFieldRef: 
          containerName: busybox
          resource: requests.cpu
          divisor: 1m
    - name: IP
      valueFrom:
        fieldRef: 
          fieldPath: status.podIP
    - name: POD
      valueFrom:
        fieldRef: 
          fieldPath: metadata.name
    - name: NODE
      valueFrom:
        fieldRef: 
          fieldPath: spec.nodeName
