apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    ques: prob11
  namespace: dump1
spec:
  volumes:
    - name: shell
      emptyDir: {}
  containers:
    - name: busybox
      image: busybox
      args:
      - /bin/sh
      - -c
      - sleep 500
      volumeMounts:
      - name: shell
        mountPath: /export/volume
      livenessProbe:
        exec:
          command:
          - cat
          - /export/volume/app.log
