apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    ques: prob11
  namespace: dump1
spec:
  volumes:
    - name: shell
      emptyDir: {}
    - name: kwsecret
      secret:
        secretName: kw-secret
  containers:
    - name: busybox
      image: busybox
      env:
      - name: MYSECRET
        valueFrom:
          secretKeyRef:
            name: kw-secret
            key: secret
      args:
      - /bin/sh
      - -c
      - sleep 500
      volumeMounts:
      - name: shell
        mountPath: /export/volume
      - name: kwsecret
        mountPath: /opt/mysecretvolume
      livenessProbe:
        exec:
          command:
          - cat
          - /export/volume/app.log
  initContainers:
    - name: init
      image: busybox
      args:
      - /bin/sh
      - -c
      - touch /export/volume/app.log
      volumeMounts:
      - name: shell
        mountPath: /export/volume
