apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kw
  namespace: dump1
  labels:
    ques: prob15
spec:
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/kw
    type: Directory
  accessModes:
    - ReadWriteOnce
