apiVersion: v1
kind: Pod
metadata:
  name: multi
  labels:
    ques: prob9
  namespace: dump1
spec:
  volumes:
    - name: nginxconfig
      configMap:
        name: nginx-config
    - name: nginxtls
      secret:
        secretName: nginx-secret
    - name: redisconfig
      configMap:
        name: redis-config

  containers:
    - name: nginx
      image: nginx:1.11.9-alpine
      ports:
        - containerPort: 80
        - containerPort: 443
      resources:
        limits:
          cpu: "0.25"
      volumeMounts:
        - name: nginxconfig
          mountPath: "/etc/nginx/conf.d/"
        - name: nginxtls
          mountPath: "/etc/nginx/ssl"

    - name: redis
      image: redis:6.0.6-alpine
      ports:
        - containerPort: 6379
      command:
        - redis-server
        - "/redis-master/redis.conf"
      resources:
        limits:
          cpu: "0.25"
      volumeMounts:
        - name: redisconfig
          mountPath: /redis-master
    - name: memcached
      image: memcached
      ports:
      - containerPort: 11211
      resources:
        limits:
          cpu: "0.25"
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      resources:
        limits:
          cpu: "0.25"
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "mysqlpwd"
