---
apiVersion: v1
data:
  index.html: |

    <!DOCTYPE html>
    <html>
    <body style="background-color:powderblue;">

    <h1>Welcome to NGINX WebServer</h1>
    <p>Version: 1.0</p>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: mainpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-dpl
  labels:
      app: my-nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx

  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      volumes:
        - name: mainpage
          configMap:
            name: mainpage

      containers:
      - name: my-nginx
        image: nginx:1.19-alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mainpage
            mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: myweb
spec:
  selector:
    app: my-nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
