apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-dpl
  labels:
      app: my-nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx

  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      serviceAccount: my-sa1
      containers:
      - name: my-nginx
        image: nginx:1.19.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
#        livenessProbe:
#          httpGet:
#            path: /index.html
#            port: 80
#          initialDelaySeconds: 3
#          periodSeconds: 3
