apiVersion: v1
kind: PersistentVolume
metadata:
  name: volroot
  labels:
    vol: volroot
spec:
  hostPath:
    path: /
    type: Directory
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - c1w1
