apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-test
spec:
  selector:
    matchLabels:
      app: ds-app
  template:
    metadata:
      labels:
        app: ds-app
    spec:
      containers:
      - name: ds-app-ctr
        image: busybox
        command:
        - sh
        - -c
        - |
          HN=`hostname`
          echo "Node: $NODE | Hostname: $HN"
          sleep 600
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

